### ISSUE TITLE
Plan LFX mentorship program 2024 Term 1: Mar-May

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1070]
Time to plan the next term: **2024 Term 1: Mar-May**

Here's the previous timeline for term 1: https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/01-Mar-May#term-01---2023-march---may

**Comment by nate-double-u** [comment]
Proposed schedule:

| activity | date |
| --- | --- |   
| project proposals | Monday Jan 15 - Wednesday Jan 31, 8:00 AM PDT |
| mentee applications open | Monday Feb 5 - Tues Feb 13, 5:00 PM PDT |
| application review/admission decisions | Wed Feb 14 - Tues Feb 27, 5:00 PM PDT |
| Mentorship program begins with the initial work assignments | Monday March 4 (Week 1) | 
| Midterm mentee evaluations and first stipend payments | Wednesday April 10 (Week 6) |
| Final mentee evaluations and mentee feedback/blog submission due, second and final stipend payment approvals | Wed May 22, 5:00 PM PST (Week 12) |
| Last day of term | Friday May 31 |

Notes:
* The gap between project proposals closing and applications opening is for CNCF/LF staff to load proposals into the LFX platform and get LFX approvals

Events of note:
* LF all hands meeting (Nate W., and other LF folk away): Jan 22-24
* Family day (parts of Canada): Feb 21
* KubeCon + CloudNativeCon: March 19-22
* Easter long weekend: March 29 - April 1
* Victoria day (Canada): May 23

**Comment by yurishkuro** [comment]
> application review/admission decisions

Suggestion: it's not clear what this period include exactly, I think in the past this was "mentors evaluating applications and submitting decisions to LFX", after which there is another period where those decisions are entered in the system and the applicants are notified if they were selected or not. The latter is especially important since we've been receiving questions exactly about that, so I would add this explicitly as a row to the table.

Separately, I wonder if it's intentional that we're cutting the notifications so close to the start of the term, instead of say 2+ weeks ahead. I presume some mentees may want to make different plans depending on being accepted to the program or not, and we're giving them very little time. As a mentor, I don't think it matters much to me if the whole application process was shifted 2-weeks earlier, but it can make a large difference for the mentees.

**Comment by Riaankl** [comment]
@nate-double-u It look good. It look good, but I do have one concern: The application period has shrunk from 21 days last year to just 9 days this year. Do you think this shorter timeframe will be sufficient?
