### ISSUE TITLE
Update Mentoring Calendar with LFX Term 1 dates

### ISSUE THREAD

**Issue by nate-double-u** [cncf/mentoring#1086]
Follow up to https://github.com/cncf/mentoring/issues/1070 & https://github.com/cncf/mentoring/pull/1081: update the CNCF Mentoring Calendar.

https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/01-Mar-May

**Comment by Riaankl** [comment]
@Swil78 I was looking at addressing this issue when I noticed that there is already calendar events of the Term 1 dates on the mentoring calendar that you have put in. I think there was updates after you added the events therefore the dates does not match the dates in the [repo](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/01-Mar-May#readme) 
The events was added as induvidual days and not a running series of dates (showing as a bar over several days instead of events in every day, which is a little harder to follow)  

I want to update the calender, but do not want to just  "undo" all the effort you have put in.
Would you like to update the calendar to match this issue or should I go ahead and do it?

**Comment by Swil78** [comment]
@Riaankl thanks for letting me know. I've updated the calendar with the revised dates and changed all the events I entered as a running series. Please let me know if you see anything else.
Thanks!

**Comment by nate-double-u** [comment]
Thanks @Swil78 & @Riaankl!
