### ISSUE TITLE
Application pending even after completing all tasks

### ISSUE THREAD

**Issue by redoC-A2k** [cncf/mentoring#1250]
Why my application is being shown pending ? My name is afshan ahmed khan and email I'd is afshanahmeda2k@gmail.com on lfx mentorship website 
![Screenshot_20240530-134944](https://github.com/cncf/mentoring/assets/60838316/853b9315-811c-4d4f-abbc-df6535a556c5)
![Screenshot_20240530-135014](https://github.com/cncf/mentoring/assets/60838316/ad320294-2565-4f77-ae17-6c72788fe54d)

**Comment by asr2003** [comment]
@redoC-A2k It's because your application submitted and will be status pending. Once the mentor select a mentee for the project, the status will be updated. It's not a problem, if it's submitted then it's fine. Your application has considered.

I think this give you context for your query, this issue can be closed.
cc:/ @aliok @nate-double-u

**Comment by redoC-A2k** [comment]
Ohk thanks , I was expecting to see application submitted that's why I filed the issue .

**Comment by asr2003** [comment]
Hmm.. Yes, I agree with you. It will be good, if we have a status for Application Submitted. I have also seen many are confused about Application pending status after submitting. It will be great if team adds the another status in application of LFX Mentorship of **Submitted**

**Comment by nate-double-u** [comment]
Thanks for the feedback, I invite you to open a support ticket as we a the CNCF aren't the developers of the platform.

https://support.linuxfoundation.org (to sign in), https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/create/131 (to comment).
