### ISSUE TITLE
Outline responsibilities for GSOC admins

### ISSUE THREAD

**Issue by caniszczyk** [cncf/mentoring#201]

**Comment by nate-double-u** [comment]
Sorry this is a bit of a stale issue, but I think Google has outlined GSoC org admin responsibilities well here:
* https://developers.google.com/open-source/gsoc/help/responsibilities#org_admin_responsibilities
* https://developers.google.com/open-source/gsoc/help/oa-tips

**Comment by Nandini99-git** [comment]
I want to contribute in this. But not able to understant what to do.

**Comment by aliok** [comment]
@Nandini99-git Thanks for offering help.

This issue is about documenting what GSoC admins need to do at CNCF.

I believe this document is best written by GSoC admins as they have more context.

I will actually assign this to myself as I am a new GSoC co-admin at CNCF and it is a right time to create such document.

**Comment by aliok** [comment]
I am drafting some content here: https://hackmd.io/zYEGdaz-TUaNuTJnK7-eug

**Comment by nate-double-u** [comment]
@jaytiaki @Riaankl @natalisucks, is this something that should go in our v2 project?

**Comment by aliok** [comment]
I see we have a `mentoring-wg/org-admins.md` in the proposed v2 structure. It can go there I guess. Or, it can be a separete `gsoc-org-admin-guide.md` in that directory, which we can reference in `org-admins.md` document.

BTW, I wrote lots of stuff in the draft document, but maybe a better idea is to add things gradually. Like, general outline first. Then, parts of the checklist that involves tasks until today. Then gradually add content to the checklist whenever we pass to a new phase in GSoC. Just a thought...

I tried to write a checklist because I like that kind of *fool-proof* approach (fool = me forgetting things). There are some examples from [ASF](https://community.apache.org/gsoc-admin-tasks.html) and [OpenMRS](https://wiki.openmrs.org/display/RES/GSoC+Admin+Guidelines).

**Comment by a-verma26** [comment]
hi @aliok   , I want to contribute for gsoc 2023. Can you please assign me some good first issue for it?

**Comment by nate-double-u** [comment]
https://github.com/cncf/mentoring/pull/871 fixes this, but let's not close the issue till v2 (https://github.com/cncf/mentoring/pull/733) is merged in.

**Comment by nate-double-u** [comment]
> hi @aliok , I want to contribute for gsoc 2023. Can you please assign me some good first issue for it?

Hello @a-verma26, thank you for your interest in contributing to GSoC 2023. I have provided a response to a similar question you asked on another issue, which you can find here: https://github.com/cncf/mentoring/issues/874#issuecomment-1466601290.

I would also like to kindly suggest that it is best not to ask the same question in multiple places as it can create more work for the project maintainers. A better place to ask is in the cncf/mentoring discussion boards where you can get more visibility and support.
