### ISSUE TITLE
FAQ section in README.md?

### ISSUE THREAD

**Issue by shreemaan-abhishek** [cncf/mentoring#443]
It'd be really cool to have a FAQ section mentioning FAQs (of course) so that maintainers of this repository don't have to answer questions repeatedly.

**Comment by idvoretskyi** [comment]
+1, thanks, good point.

**Comment by nate-double-u** [comment]
Is a FAQ good content for the [Discussions](https://github.com/cncf/mentoring/discussions) board?

**Comment by nate-double-u** [comment]
Also, what are some good frequently asked questions we could start with?

**Comment by money8203** [comment]
@nate-double-u @idvoretskyi, these are some of the questions you can answer :

1. I am a complete beginner, no prior knowledge about CNCF but interested in contributing to it so, from where should I start my contribution journey ?
2.  I want to be a part of CNCF organization, where to begin, whom to contact ?
3. I want to contribute to CNCF projects ?
4. Interested in becoming LFX mentee / mentor ?
5. Getting started with (I want to contribute to) CNCF GSOC projects, whom to contact, where to start, what's the criteria ?
6. How can a non-code person contribute to CNCF ?
7. I am interesting in becoming CNCF Ambassador, can you tell me the process ?

**I am interested in promoting and contributing to CNCF and its mission, vision, projects. All I want is just a mentor during my initial starting phase who can guide me, provides answer to my questions related to projects-technologies-community building and how can I be more productive, so that I could get the required knowledge and mindset to follow my pursue for teaching, guiding and mentoring different peoples, connecting and welcome them into tech and provide them with all the resources and mentorship needed to follow their passion of getting into tech and open source building.**

_Also if provided with the right resources I can gasp all the knowledge required to know about CNCF & you can ping my profile so that if anyone is having any trouble and confusion regarding CNCF contribution/projects/ probably anything, he/she can contact me instead of disturbing all the mentors and flooding their dm's, as talking to someone about any particular topic is way better than reading the documentation and being confused about it, especially as a beginner and I can handle this as I love solving peoples problem and helping them in any particular way._

**Comment by jaytiaki** [comment]
Hey Nate, this is great, thanks for sharing this. Looking forward to
breaking it down in more detail with you soon :)

Cheers,
Jay

**Comment by nate-double-u** [comment]
I've added this to our repo refactor project board. An FAQ would be a very good addition to the site and I think the refactor is the place to do it.

Thanks for the question suggestions @money8203

**Comment by money8203** [comment]
Pleasure is all mine, do you want me to handle this along with the documentation @nate-double-u ??

**Comment by nate-double-u** [comment]
Everyone is welcome to make contributions @money8203!

In this case, take a look at our umbrella PR https://github.com/cncf/mentoring/pull/733, and the project board: https://github.com/orgs/cncf/projects/16

Any work relating to the refactor project should target the [v2 branch](https://github.com/cncf/mentoring/tree/v2) in PRs.

I'd also invite you to join our [monthly meetings](https://hackmd.io/@tag-cs-mentoring-wg/monthly-meeting-2023), as it would help with context and co-ordination.
