### ISSUE TITLE
Update the Root README.md

### ISSUE THREAD

**Issue by Riaankl** [cncf/mentoring#748]
After moving all information around in the repo review/.
Do a hyperlinked "site map" for the rest of the repo

**Comment by money8203** [comment]
Hey, I am interested working on this issue, just needed a bit more clarification if possible!

**Comment by Riaankl** [comment]
@money8203 thank you for reaching out to help.
This is part of a [larger project](https://github.com/orgs/cncf/projects/16) to refector the all of the Mentoring WG GH repo.
We created the issue out of a discussion in yesterday's Mentoring WG meeting.
We are doing the work against the V2 branch at the momnent. 
Once all the movement in the repo is done and information is updated this issue would be the last step to write an overarching README.md that discribe the repo and it's content in its final state.

Please join us for the bi-weekly Mentoring WG meetings to learn more and to help with contributions.
[Tag-cs-mentoring-wg/monthly-meeting](https://www.google.com/url?q=https://hackmd.io/@tag-cs-mentoring-wg/monthly-meeting&sa=D&source=calendar&ust=1669657256265705&usg=AOvVaw2hU8cMAifHBJMtf5HKx3Xl)

**Comment by money8203** [comment]
Oh, got it!
Thank you so much for clarifying the issue, and I am eager to attend the next meet for more insights into the CNCF.

**Comment by Abinash-bit** [comment]
@Riaankl hello I am Abinash Mahapatra , I am interested in resolving this issue. please help and guide me.

**Comment by evershalik** [comment]
hey, I am interested in working on this issue, can you please share some more details about it

**Comment by nate-double-u** [comment]
Thank you for your interest in cncf/mentoring @Abinash-bit & @evershalik. Since part of our mission is education, we wanted to explain why your comments haven't been addressed. We welcome questions, but they need to be specific, which these aren't. Indeed, Riaan has already answered your questions: he's provided more detail about the issue and has linked to our bi-weekly meetings, which are open to anyone to attend.

Here are some good guides to help you start contributing:
* Read the [CONTRIBUTING](https://github.com/cncf/tag-contributor-strategy/blob/main/CONTRIBUTING.md) guide.
* Volunteer to work on an open issue that you know how to fix.
* Attend [meetings or join our Slack channel](https://hackmd.io/@tag-cs-mentoring-wg/monthly-meeting-2023, https://cloud-native.slack.com/archives/CT6CWS1JN).
* Contribute a bug fix or open an issue for a problem that is impacting you.

**Comment by Riaankl** [comment]
Updated, ready to be reviewed and merge from v2 Branch

**Comment by Riaankl** [comment]
V2 Branch merge. This work is done!!
https://github.com/cncf/mentoring/pull/899
