### ISSUE TITLE
[GSOC 23] Recommended skills missing for Cloud Native Buildpacks Enhancements for Dockerfiles

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#874]
https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md#enhancements-for-dockerfiles

Natalie Arellano (@natalieparellano), could you please specify the recommended skills for that idea?

**Comment by a-verma26** [comment]
hi @aliok  , I want to contribute for gsoc 2023. Can you please assign me some good first issue for it?

**Comment by nate-double-u** [comment]
Hi @a-verma26, thanks for your interest in the program; however, this is not really a great issue to ask about contributing to GSoC generally -- this issue is aimed at making a specific change to a particular proposal.

For help getting started I'd suggest taking a look at our [cncf/mentoring discussions boards](https://github.com/cncf/mentoring/discussions).
