### ISSUE TITLE
Revisit discussion categories in this repo

### ISSUE THREAD

**Issue by aliok** [cncf/mentoring#969]
Looks outdated

![Screenshot 2023-05-09 at 20 36 53](https://github.com/cncf/mentoring/assets/376732/6f54dfa0-096e-4acf-a8ee-11ce1b3898d2)

**Comment by nate-double-u** [comment]
Probably we should remove:
* Ideas
* Polls
* Show and tell

I'm happy to keep old GSoC and GSoD categories around as an archive. I think for the older one's I've gone through and set it so that individual conversations are locked now, but I'm not sure if we can do that across a whole category. I lock them to prevent spam.

**Comment by aliok** [comment]
> Probably we should remove:
> Ideas
> Polls
> Show and tell

Just did this.

> I'm happy to keep old GSoC and GSoD categories around as an archive. I think for the older one's I've gone through and set it so that individual conversations are locked now, but I'm not sure if we can do that across a whole category. I lock them to prevent spam.

I understand what you mean when I check the administration of the discussion categories. 
Created https://github.com/orgs/community/discussions/57008

**Comment by aliok** [comment]
Closing this ticket as it is resolved for now. If there's additional information comes up from https://github.com/orgs/community/discussions/57008, I can open a new ticket
